version: "3"
services:
  web:
    restart: always
    build: ./rates
    ports:
      - "3000:3000"
    environment:
      APP_ENV: "dev"
      POSTGRES_HOST: "database"
      POSTGRES_USER: ${POSTGRES_DEFAULT_USER:-xenetau}
      POSTGRES_PASSWORD: ${POSTGRES_DEFAULT_PASSWORD:-word2pass}
      POSTGRES_DB: ${POSTGRES_DEFAULT_DB:-xenetadb}
      POSTGRES_PORT: "5432"
    depends_on:
      - database
    links:
      - database:database
    command: gunicorn -b :3000 wsgi
  
  data:
    image: postgres:9.6
    volumes:
      - database-data:/var/lib/postgresql/data/
    command: "true"

  database:
    image: postgres:9.6
    environment:
      POSTGRES_USER: ${POSTGRES_DEFAULT_USER:-xenetau}
      POSTGRES_PASSWORD: ${POSTGRES_DEFAULT_PASSWORD:-word2pass}
      POSTGRES_DB: ${POSTGRES_DEFAULT_DB:-xenetadb}
    volumes:
      - database-data:/var/lib/postgresql/data/
      - ./db/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"
    restart: unless-stopped

  pgadmin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
    volumes:
      - pgadmin:/root/.pgadmin
    ports:
      - "5050:80"
    restart: unless-stopped
    depends_on:
      - database

volumes:
  database-data:
  pgadmin:
